encoding: UTF-8

url: "https://tzling.com"
title: Tzling
description: 一個自由工作者的隨筆。台灣‧韓國‧瑞典生活記事及翻譯大小事
lang: zh_TW

theme: null

kramdown:
  auto_ids: true

permalink: pretty

plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from

exclude:
  - .git
  - .gitignore
  - package.json
  - package-lock.json
  - yarn.lock
  - node_modules
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md

defaults:
  - scope:
      path: "assets"
    values:
      image: true

future: true